### PR TITLE
Migrate CI to GitHub Actions

### PR DESCRIPTION
**Pull request by petricm**
BEGINRELEASENOTES
- Migrate CI to GitHub Actions

ENDRELEASENOTES

### CODE REVIEW

**Comment by petricm** [comment]
I think this should be it, I just need to wait if all passes then I will change the repo config

**Comment by andresailer** [comment]
Before we copy this to all packages, we should investigate the use of this action as a template, so that we can maybe configure it in one place.

**Comment by petricm** [comment]
All seems fine but I see a problem on ubuntu, with readline

https://github.com/petricm/LCIO/runs/1487438069?check_suite_focus=true

any idea?

**Comment by gaede** [comment]
The problem is caused by an incompatible libreadline, used in the lsh example. As this is somewhat out of date,
I remove it from the build process in #126.

**Pull request merged**
