### PR TITLE
Linker

### LINKED ISSUE #118: Undefined linker flag -Wl,-no-undefined when compiling with GNU gcc/g++ on macOS
!!!IMPORTANT!!!: To facilitate faster and easier response to your issue please provide in addition to the description of the issue also the following information

 - OS version: macOS Darwin 10.15.7
 - Compiler version: GCC 10.2
 - Package version: v2.15.04

Hi, this is halfway a question or a discussion. To build LCIO on macOS with gcc/g++ instead of the XCode/System clang,
I always have to comment out the lines

`IF( "${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU" )
  LIST( APPEND COMPILER_FLAGS -Wl,-no-undefined )
ENDIF()`

in ilcsoft_default_cxx_compiler_flags.cmake
because the g++ (which is the default linker in that case) does not know this flag:

`/usr/local/bin/g++ -fdiagnostics-color=auto -Wl,-no-undefined -Wno-non-virtual-dtor -Wuninitialized -Wno-long-long -pedantic -Weffc++ -Wshadow -Wextra -Wall  -O2 -g -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -dynamiclib -Wl,-headerpad_max_install_names -current_version 0.0.2 -o ../lib/libsio.0.0.2.dylib -install_name @rpath/libsio.0.0.dylib CMakeFiles/sio.dir/src/api.cc.o CMakeFiles/sio.dir/src/block.cc.o CMakeFiles/sio.dir/src/buffer.cc.o CMakeFiles/sio.dir/src/compression/zlib.cc.o CMakeFiles/sio.dir/src/exception.cc.o CMakeFiles/sio.dir/src/io_device.cc.o CMakeFiles/sio.dir/src/memcpy.cc.o CMakeFiles/sio.dir/src/version.cc.o  /opt/local/lib/libz.dylib 
ld: unknown option: -no-undefined`

I think the reason is the following: when you install gcc with one of the default tools on macOS (like homebrew, Macports or fink) it installs also a gcc-affine linker version (ld64 in /opt/local/bin) which understands this option. If you build gcc yourself, it still uses /usr/bin/ld, so the system linker, in which case -Wl,-undefined,error would be the correct choice. Of course, this is partially in the user responsibility, but I think there is no cmake option that I could use to specify that flag. 
CMAKE_EXE_LINKER_FLAGS seems like the parameter to set, but it looks I cannot set this. Could you check for the linker?
As mentioned above, this is not really a bug in my eyes, but a special case for user setups. But maybe there is a fast solution.

### PR DESCRIPTION
**Pull request by petricm**
resolves #118 
BEGINRELEASENOTES
- Update compiler flag handling
- Resolve which type of linker is used and assign proper linking flags
- Improve RPATH handling on macOS and add flag `LCIO_SET_RPATH` default `ON`

ENDRELEASENOTES

### CODE REVIEW

**Comment by rete** [comment]
@gaede Do you remember what is the default rpath settings in a iLCSoft installation? Do we set this or not?
In other words, what should be the default value here and do we need to update iLCInstall scripts to set `-DLCIO_SET_RPATH=ON/OFF`?

**Comment by gaede** [comment]
We always built iLCSoft with rpath: https://github.com/iLCSoft/iLCUtil/blob/master/cmakemodules/ilcsoft_default_rpath_settings.cmake, so no need to specify anything in ilcinstall.
We need make sure, however that the settings in this PR and in ilcutil are compatible...

**Comment by petricm** [comment]
What is here for the linux rpath follows official CMake instruction on full rpath
https://gitlab.kitware.com/cmake/community/-/wikis/doc/cmake/RPATH-handling#always-full-rpath
the only difference to iLCSoft is that `ilcsoft_default_rpath_settings.cmake` is missing
```cmake
# use, i.e. don't skip the full RPATH for the build tree
set(CMAKE_SKIP_BUILD_RPATH FALSE)
# when building, don't use the install RPATH already
# (but later on when installing)
set(CMAKE_BUILD_WITH_INSTALL_RPATH FALSE)

```
and the system dir treatment. 

As for the mac treatment, there is a long story on `@rpath` [here](https://blog.krzyzanowskim.com/2018/12/05/rpath-what/) or [here](https://medium.com/@donblas/fun-with-rpath-otool-and-install-name-tool-e3e41ae86172), but in short this is way DD4hap and ROOT are built on macOS.

**Comment by petricm** [comment]
So, if you look in detail, this is the same as it was before with the added option to disable rpath

**Comment by petricm** [comment]
I was probably not clear. This PR does not change existing LCIO rpath behaviour, it just adds options.

**Review by rete — APPROVED** [review]

**Pull request merged**
