### PR TITLE
Remove dynamic exception specification

### PR DESCRIPTION
**Pull request by petricm**
BEGINRELEASENOTES
- Replace dynamic exception specification with `noexcept(false)`

ENDRELEASENOTES

### CODE REVIEW

**Comment by petricm** [comment]
I have removed the nullptr changes. Can you please review this since it causes a lot of warnings.

**Comment by petricm** [comment]
Can you please review this @gaede. This blows up the log-files substantially.

**Comment by gaede** [comment]
@petricm : Can you please create this PR with a feature branch other than master.

**Comment by petricm** [comment]
@gaede created new branch dynamicExcept and pointed the PR there.

**Pull request closed without merging**
