### PR TITLE
Fix deprecated exception warnings

### PR DESCRIPTION
**Pull request by gaede**
BEGINRELEASENOTES
- fix some warning:
       - deprecated dynamic exception specifications in Exceptions
- fix the build from generated C++ files

ENDRELEASENOTES

### CODE REVIEW

**Review by rete — APPROVED** [review]

**Comment by rete** [comment]
@gaede @andresailer @petricm We have an issue with TravisCI. Also the case for #124 and #122.

We spent our free credits for the month it seems: https://travis-ci.com/organizations/iLCSoft/plan

I'm actually really surprised because we don't have much activities these times on Github... 

Maybe we should think about an alternative. Any thoughts on this?

**Comment by andresailer** [comment]
We have to move to github actions I would say

**Comment by rete** [comment]
I've made a very raw estimate of our credits. Just taking into account the CRON job:

- 39 repositories
- 7 minutes of build on average (6 + 1)
- 4 CRON jobs per month
- TravisCI credit factor per minutes for linux jobs: 10

Total credit estimate for CRON jobs: 10920
Available free credit per month with TravisCI: 10000

Even if we have more credit with Github actions, we might enter the same troubles quickly...

**Comment by rete** [comment]
I'm confused now: https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-billing-and-payments-on-github/about-billing-for-github-actions

**Comment by rete** [comment]
Oooh... The limit is for private repos: https://github.com/organizations/iLCSoft/settings/billing
Sorry

**Comment by gaede** [comment]
> We have to move to github actions I would say

How do we do this and who can do it ?
Does this apply to all our iLCSoft (and AIDASoft, key4hep,...) repositories ?

**Comment by petricm** [comment]
I can do it for LCIO, but yes eventually all needs to be migrated probably

**Comment by gaede** [comment]
That would be great. We can then follow your recipe for other repos...

**Comment by petricm** [comment]
The new version will be a bit more comprehensive so I found already this
```
src/python/pyLCIO/io/Reader.py:54: [W1653(next-method-defined), Reader.next] next method defined
```
this is a py3 error

**Comment by petricm** [comment]
you can start rebasing

**Comment by gaede** [comment]
Can we re-trigger the new CI for the three open PRs first ?
Now they show "passed" but nothing seems to have run - or am I missing sth. ?

**Comment by petricm** [comment]
close/open PR

**Pull request merged**
