### PR TITLE
Remove dynamic exception specification

### PR DESCRIPTION
**Pull request by petricm**
replaces #34 
BEGINRELEASENOTES

 -  Replace dynamic exception specification with `noexcept(false)`

ENDRELEASENOTES

### CODE REVIEW

**Comment by gaede** [comment]
@petricm you also have to change all the aid files in `src/aid` accordingly using 
`@ifdef cpp` and `@ifdef cpp` accordingly.  Otherwise header generation will no longer work correctly...

**Comment by petricm** [comment]
Done

**Comment by petricm** [comment]
or you want e.g.:
```cpp
public void addElement(LCObject* obj)
#if __cplusplus > 199711L
  noexcept(false)
#else
  throws ReadOnlyException
#endif
{...}
```

**Comment by petricm** [comment]
Sorry I did not understand your comment before. Now it's done.

**Comment by gaede** [comment]
This does not work :-(
```
[  3%] Generating header file EVENT/Cluster.h
[  3%] Generating header file IO/LCWriter.h
[  3%] Generating header file EVENT/CalorimeterHit.h
[  4%] Generating header file EVENT/LCCollection.h
ERROR: Encountered errors during parse.
Encountered "noexcept" at line 23, column 47.
Was expecting one of:
    "const" ...
    "throws" ...
    "[" ...
    ";" ...
    
```
Not sure what to do now. Clearly we want this fix for C++ eventually but it breaks the header file generation with the aid tool. So we need an update to `./tools/freehep-aid.jar`  (from which source ? ).

**Comment by petricm** [comment]
We could remove the `noexcept(false)` as there if no difference. This was just put to be explicit that it throws, but by default all functions throw
```cpp
void f() noexcept;
void f(); // error: different exception specification
void g() noexcept(false);
void g(); // ok, both declarations for g are potentially-throwing
```

**Comment by gaede** [comment]
Superseded by #43.

**Pull request closed without merging**
