### PR TITLE
New LCIO MT (External SIO)

### PR DESCRIPTION
**Pull request by rete**
BEGINRELEASENOTES
- Externalized SIO package: https://github.com/iLCSoft/SIO
- Use new SIO implementation:
  - Ensure thread-safety for multiple LCReader / LCWriter instance (removal of globals)
  - Possibility for adding new compression algorithm in future
  - Standard LCReader and LCWriter use the MT versions (see below) for implementation under the hood
- Added new `MT::LCReader` and `MT::LCWriter`
   - Different interface for reading and writing events. Use smart pointers for event/run ownership
   - MT::LCWriter allows for writing concurrently event in a file from multiple threads. Event encoding and compression is standalone, so thread-safe, and I/O writing is done under a (fast) mutex.
- Introduce new creation flag for standard LCReader: **LazyUnpacking**
   1. Reads an event from file 
   2. Move the compressed buffer inside an LCEvent object
   3. Perform un-compression and decoding only on demand when `LCEvent::getCollection()` is called
- LCIO objects uids increment is now atomic (`AccessChecked`)
- Introduced runtime extensions for LCEvent, accessible via `LCEvent::runtime()` method.
- Introduced `LCIO_DEPRECATED` macro for deprecated methods in LCIODeprecated.h
- LCIO extensions:
  - Removed global destructor mapping for each relation type, because not thread safe
  - Turned internal extension type to `std::shared_ptr<void>` to use type-safe extension destructor
- Added example binaries:
   - `lcio_parallel_processing`: a small example to illustrates how to use the new MT classes. Implements a simple scheduling algorithm for parallel event processing
   - `lcio_parallel_read`: a small example of how to dump events and runs from multiple files at the same time in parallel
   - `lcio_performance`: printout file reading performance with and without lazy unpacking
- Unit testing:
   - added unit test for lazy unpacking feature
   - switched back ON the unit test on RT extensions
- Bug fixes
   - CXX standard was hardcoded to 14. Now set it to 14 if not specified via command line with i.e `-DCMAKE_CXX_STANDARD=17`  
- Packaged builtin SIO in LCIO
   - Compile the SIO library (only) if not found on your system

ENDRELEASENOTES

TODO: 
- [x] Remove dev markdown file
- [x] Remove unused dev binaries
- [x] Package SIO into LCIO
- [x] Finish backward compatibility tests

### CODE REVIEW

**Comment by gaede** [comment]
Hi @andresailer, @petricm, would it be possible to add the new standalone SIO (https://github.com/iLCSoft/SIO) to the nightly builds used for iLCSoft ?
It can be easily installed with ilcinstall.

**Comment by andresailer** [comment]
Yes, you just have to add the appropriate line to https://github.com/iLCSoft/iLCInstall/blob/master/builds/release-ilcsoft-lcg.cfg and https://github.com/iLCSoft/iLCInstall/blob/master/builds/release-ilcsoft.cfg I think.

**Comment by gaede** [comment]
Thanks. Added this to ilcinstall (https://github.com/iLCSoft/iLCInstall/pull/111).

**Comment by gaede** [comment]
It seems that now a fixed LCG release is used for the CI:
https://github.com/iLCSoft/LCIO/blob/master/.travis-ci.d/init_x86_64.sh#L47-L52
Are there any LCG nightly builds ?

**Comment by andresailer** [comment]
No, we don't have anything on top of the lcg nightly builds at the moment.

**Comment by petricm** [comment]
It would be I think advantageous to implement a feature via `ExternalProject` or some other means (whatever @andresailer thinks best) that automatically resolves this dependency on SIO (by default OFF), if a user requests this, because until now LCIO was fairly standalone and this is the first hard dependency.

Furthermore how are you envisioning releasing LCIO with this new dependency. I presume we can test LCIO master with SIO master, but a version of LCIO  requires probably a specific version of SIO?

I would advice for the moment to build SIO and LCIO in one go as this is the easiest way to test master vs. master and the SIO build is quite quick.

**Comment by gaede** [comment]
Hi Marko, we had discussed some options for 'hiding' the SIO dependency, such as ExternalProject or shipping a copy of the sources with LCIO. In the end, we thought it would be the cleanest option to make this new dependency explicit, as it is the easiest to maintain in the long run. Also, I would like to use SIO also as an option for PODIO, so we need it in the key4hep stack (and LCG ?) anyhow.
We could reconsider this, at least for a transition period, if you think it would be important.

**Comment by gaede** [comment]
@rete: what is the status of the two to-do items in the PR comment ?

**Comment by rete** [comment]
@gaede I'm still listing the changes for the release notes and populating this TODO list. It is normally just about removing unused stuff. Should be straight forward...

**Comment by rete** [comment]
Nightly builds addressed in https://github.com/iLCSoft/iLCInstall/pull/112

**Comment by rete** [comment]
I've SIO v00-00-02 sources with a custom CMakeLists.txt to build the library only and link it to LCIO. 
Note:
- the SIO includes are not installed
- the SIO binaries are not built
- the SIO library is installed along with the LCIO library
- the SIOConfig.cmake is not generated

**Comment by rete** [comment]
@gaede For backward compatibility tests, I've tested different configurations, always by dumping an event and making a diff of the LCIO master and LCIO of this branch.

Tests:
- 250 GeV production data: compare dumpevent of SIM, REC and DST files
- ILDConfig v02-01, 3 event test: compare dumpevent of ddsim output
- ILDConfig v02-01, 3 event test: compare dumpevent of marlin REC file
- ILDConfig v02-01, 3 event test: compare dumpevent of marlin DST file

The objects ids are a little bit different because of the way the event are skipped in the new implementation. I had to remove the object ids from the dumpevent for the tests, else the diff would have  to difficult.
Except this number, there is no diff in all cases.

**Pull request merged**
