### PR TITLE
SimTrackerHit: Add quality bitfield

### PR DESCRIPTION
**Pull request by andresailer**
I tried to add the quality field for #11 .
Am I missing something?

I couldn't figure out how to run AID to generate the headers so I modified them directly

Where can/should I added some pre-defined bits 
e.g.
kIsHitFromSecondary when the hit was not actually created by the MCParticle it is assigned to?

BEGINRELEASENOTES
- SimTrackerHit: Add Quality bitfield

ENDRELEASENOTES

- [x] Still need to implement the status bits

### CODE REVIEW

**Comment by gaede** [comment]
- set LCIO_GENERATE_HEADERS=ON to generate the header files from aid
   and then rebuild
- you also need to implement the corresponding changes in Java 
- the tests did not succeed ;-(

**Comment by gaede** [comment]
- for the constants it would be best to follow what is done in MCParticle: 
         - https://github.com/iLCSoft/LCIO/blob/master/src/cpp/include/pre-generated/EVENT/MCParticle.h#L87-L95

**Comment by gaede** [comment]
please also update:
- https://github.com/iLCSoft/LCIO/blob/master/src/cpp/include/CPPFORT/lcsth.h
- https://github.com/iLCSoft/LCIO/blob/master/src/cpp/src/CPPFORT/lcsth.cc
- https://github.com/iLCSoft/LCIO/blob/master/doc/lcio.xml

**Comment by andresailer** [comment]
What about the fortran parts?

**Comment by gaede** [comment]
I don't think this is used anymore - or kept up to data.

**Comment by andresailer** [comment]
Tests are now passing, but the tests for java were already broken before and are not running in travis.

**Comment by andresailer** [comment]
Still need to implement the status bits

**Comment by gaede** [comment]
Yes, it seems that the java build and tests are broken already on the HEAD. Could get the build to work with some extra commands but the tests are still broken...
Can you inform norman and jeremy about your changes and ask them to check the java build, test and you changes ?

**Comment by gaede** [comment]
@andresailer after having implemented the status bits, can you also add corresponding printout code the ostream operators, defined here:
https://github.com/iLCSoft/LCIO/blob/master/src/cpp/src/UTIL/Operators.cc#L1799-L1961

**Comment by andresailer** [comment]
Implemented two quality bits and printout
```
--------------- print out of SimTrackerHit collection ---------------

  flag:  0x20000000
 parameter CellIDEncoding [string]: subdet:5,side:-2,layer:9,module:8,sensor:8,readoutUnit:8,daqChannel:16,,
     LCIO::THBIT_BARREL : 0
     LCIO::THBIT_MOMENTUM : 0
    quality bits: [os......]  o: hit from overlay s: hit from secondary not from the MCParticle associated to it


 [   id   ] |cellId0 |cellId1 |  position (x,y,z)               |   EDep   |   time   |PDG of MCParticle|   (px,  py, pz)   | pathLength  | Quality
------------|--------|--------|---------------------------------|----------|----------|-----------------|-------------------|-------------|---------
 [00000004] |00065635|00000000|(+0.00e+00, +0.00e+00, +0.00e+00)| 0.00e+00 | 0.00e+00 | 00000000000000  |   unknown         |     n/a     |[os     ]
        id-fields: (subdet:3,side:-1,layer:0,module:1,sensor:0,readoutUnit:0,daqChannel:0)

 [00000005] |16842979|00002048|(+0.00e+00, +1.00e+00, +0.00e+00)| 0.00e+00 | 0.00e+00 | 00000000000000  |   unknown         |     n/a     |[   0   ]
        id-fields: (subdet:3,side:-1,layer:1,module:1,sensor:1,readoutUnit:0,daqChannel:8)
```

(added n/a for pathlength if not stored as well

any more possible flags come to mind?

**Pull request merged**
