### PR TITLE
Fix all warnings and move to v02-07-05

### PR DESCRIPTION
**Pull request by gaede**

### CODE REVIEW

**Comment by petricm** [comment]
Could you also please fix the cmake warnings, especially the one about ADD_DEPENDENCIES:
`The dependency target "jar" of target "tests" does not exist.`

**Comment by petricm** [comment]
There is one you "missed" but can also be that it is not in you clang configuration 
```
Linking CXX executable bin/lsh

lcio/CMakeFiles/bin_lsh.dir/src/EXAMPLE/lsh.cc.o: In function `begin_paging(pagerInfo*)':

/Package/build/../src/cpp/src/EXAMPLE/lsh.cc:149: warning: the use of `mktemp' is dangerous, better use `mkstemp'
```

**Comment by petricm** [comment]
Travis has [internals problems](https://www.traviscistatus.com/incidents/hmwq9yy5dh9d)

**Comment by petricm** [comment]
Hi,
I think that LCIO is broken now:

`cmake -DUSE_CXX11=ON -DBUILD_ROOTDICT=ON -DCMAKE_CXX_FLAGS="-fdiagnostics-color=always" ..`

results in 

```
CMake Warning (dev) at cmake/MacroGeneratePackageConfigFiles.cmake:37 (EXPORT_LIBRARY_DEPENDENCIES):
  Policy CMP0033 is not set: The export_library_dependencies command should
  not be called.  Run "cmake --help-policy CMP0033" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.
Call Stack (most recent call first):
  CMakeLists.txt:265 (GENERATE_PACKAGE_CONFIGURATION_FILES)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
```

**Comment by gaede** [comment]
fixed (directly in master)

**Pull request merged**
